### ISSUE TITLE
Please update io-extras dependency to support older rust versions.

### ISSUE THREAD

**Issue by plugwash** [sunfishcode/socketpair#13]
Hi, i'm trying to build code (specifically i'm trying to run the tests of the selinux crate) that uses socketpair using rustc 1.62, however when I do I get a failure in the io-extras crate.

    error[E0277]: the trait bound `T: FromFd` is not satisfied

This is fixed in io-extras 0.17, is there any chance you could update the dependency and make a new release?

**Comment by sunfishcode** [comment]
Thanks for the report! This is now fixed in socketpair 0.18.
