### ISSUE TITLE
Support for `SOCK_SEQPACKET`?

### ISSUE THREAD

**Issue by cgwalters** [sunfishcode/socketpair#2]
I like using `SOCK_SEQPACKET` for Unix-specific IPC.  (Actually, is there a Windows equivalent?)  Currently for example I'm doing this in https://github.com/containers/containers-image-proxy-rs/blob/bceb562e164bb419ffa8ed12ef54fdadf6eb4cc6/src/imageproxy.rs#L88

Any thoughts on exposing that via this crate?

**Comment by sunfishcode** [comment]
Windows has `PIPE_TYPE_MESSAGE` which is documented to work like `SOCK_SEQPACKET` and I've been curious to try it out as there are things I want to do with `SOCK_SEQPACKET` streams as well, so this sounds like a good time to try the experiment :-).

I wrote up https://github.com/sunfishcode/socketpair/pull/3 which implements this, for Windows and Unix-type platforms. Does that look like it'd be useful to you?

**Comment by cgwalters** [comment]
Fixed by https://github.com/sunfishcode/socketpair/pull/3

**Comment by sunfishcode** [comment]
This is now released in 0.11.0.

**Comment by sunfishcode** [comment]
I just learned that macOS doesn't support `SOCK_SEQPACKET` on `AF_UNIX` or `socketpair`. So as a heads up, this feature doesn't work on those platforms.

**Comment by cgwalters** [comment]
Ah.  I don't personally care about MacOS for what I'm working on right now, but may eventually.

A classic example of the "gravity of the lowest common denominator".  The really nice thing about `SEQPACKET` is one can rely on the kernel to do framing and avoid an implementation in userspace.  But hmm...maybe if I need to I can change my little "JSON over seqpacket" to be framed by NUL bytes or something.

**Comment by sunfishcode** [comment]
It looks like we can use `SOCK_DGRAM` on macOS, which has framing behavior, and should be reliable on `AF_UNIX` sockets. I've posted #6 to implement this.
